# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-21 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('featurerequest', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clients',
            options={'verbose_name_plural': 'clients'},
        ),
        migrations.AddField(
            model_name='features',
            name='status',
            field=models.CharField(blank=True, choices=[('A', 'Active'), ('I', 'Inactive'), ('D', 'Done'), ('C', 'Cancelled')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='status',
            field=models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], max_length=50),
        ),
        migrations.AlterField(
            model_name='productarea',
            name='status',
            field=models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], max_length=50),
        ),
    ]
