# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-01 09:52
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('featurerequest', '0004_auto_20180701_0521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='features',
            name='priority',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
